# Generated by Django 5.2.5 on 2025-08-31 06:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CourseName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CourseName', models.CharField(max_length=100, unique=True)),
                ('Fees', models.CharField(max_length=100, unique=True)),
                ('Duration', models.CharField(max_length=100, unique=True)),
                ('Vedio', models.FileField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='HrRegister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100, unique=True)),
                ('CompanyId', models.CharField(max_length=100, unique=True)),
                ('Email', models.CharField(max_length=100, unique=True)),
                ('Address', models.CharField(blank=True, max_length=100, null=True)),
                ('PhoneNo', models.BigIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='HRTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200, unique=True)),
                ('Company_Name', models.CharField(blank=True, max_length=100, null=True)),
                ('Email', models.EmailField(max_length=254, unique=True)),
                ('Phone_Number', models.CharField(max_length=15, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='JobroleTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=200, unique=True)),
                ('Description', models.CharField(max_length=1000, unique=True)),
                ('Experience', models.CharField(max_length=1000, unique=True)),
                ('Job_Role', models.CharField(max_length=100, unique=True)),
                ('Company_ID', models.CharField(max_length=100, unique=True)),
                ('Salary', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='LoginTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(max_length=100)),
                ('Password', models.CharField(max_length=100)),
                ('UserType', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserRequestTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(max_length=100, unique=True)),
                ('DOB', models.CharField(blank=True, max_length=100, null=True)),
                ('Email', models.CharField(blank=True, max_length=100, null=True)),
                ('Qualification', models.CharField(blank=True, max_length=100, null=True)),
                ('Address', models.CharField(blank=True, max_length=100, null=True)),
                ('Area_of_Interest', models.CharField(blank=True, max_length=100, null=True)),
                ('PhoneNo', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='UserTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(blank=True, max_length=100, null=True)),
                ('DOB', models.CharField(blank=True, max_length=100, null=True)),
                ('Email', models.CharField(blank=True, max_length=100, null=True)),
                ('Qualification', models.CharField(blank=True, max_length=100, null=True)),
                ('Area_Of_Interest', models.CharField(blank=True, max_length=100, null=True)),
                ('Phone_Number', models.CharField(blank=True, max_length=100, null=True)),
                ('LOGIN', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carriera.logintable')),
            ],
        ),
        migrations.CreateModel(
            name='ResumeTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Resume', models.FileField(blank=True, null=True, upload_to='')),
                ('Date', models.DateField(blank=True, null=True)),
                ('USER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carriera.usertable')),
            ],
        ),
        migrations.CreateModel(
            name='RequestTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Status', models.CharField(max_length=100, unique=True)),
                ('JOB', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carriera.jobroletable')),
                ('USER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carriera.usertable')),
            ],
        ),
        migrations.CreateModel(
            name='ComplaintTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Complaint', models.CharField(max_length=1000)),
                ('Reply', models.CharField(max_length=1000)),
                ('Created_at', models.DateField(blank=True, null=True)),
                ('USER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carriera.usertable')),
            ],
        ),
        migrations.CreateModel(
            name='CertificateTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100, unique=True)),
                ('Certificate', models.FileField(unique=True, upload_to='')),
                ('Description', models.CharField(blank=True, max_length=100, null=True)),
                ('Date', models.DateField(blank=True, null=True)),
                ('USER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carriera.usertable')),
            ],
        ),
    ]
