# Generated by Django 5.2.5 on 2025-09-01 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carriera', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CourseName', models.CharField(max_length=100, unique=True)),
                ('Fees', models.CharField(max_length=100, unique=True)),
                ('Duration', models.CharField(max_length=100, unique=True)),
                ('Video', models.FileField(blank=True, null=True, upload_to='', verbose_name='coursevideo/')),
            ],
        ),
        migrations.RenameModel(
            old_name='HrRegister',
            new_name='HrRegisterTable',
        ),
        migrations.DeleteModel(
            name='CourseName',
        ),
        migrations.RenameField(
            model_name='jobroletable',
            old_name='Company_ID',
            new_name='Company_Name',
        ),
    ]
