# Generated by Django 5.2.5 on 2025-09-01 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carriera', '0002_coursetable_rename_hrregister_hrregistertable_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complainttable',
            name='Created_at',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
