# Generated by Django 5.2.5 on 2025-09-01 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carriera', '0003_alter_complainttable_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hrtable',
            name='Name',
        ),
        migrations.AddField(
            model_name='hrtable',
            name='type_of_indusrty',
            field=models.CharField(default=1, max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='complainttable',
            name='Reply',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
