# Generated by Django 5.2.5 on 2025-09-02 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carriera', '0004_remove_hrtable_name_hrtable_type_of_indusrty_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollegeTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CollegeName', models.CharField(max_length=1000)),
                ('Address', models.CharField(blank=True, max_length=1000, null=True)),
                ('Email', models.CharField(max_length=100, unique=True)),
                ('PhoneNo', models.BigIntegerField(blank=True, null=True)),
            ],
        ),
    ]
