# Generated by Django 5.2.5 on 2025-09-02 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carriera', '0005_collegetable'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collegetable',
            name='CollegeName',
        ),
        migrations.AlterField(
            model_name='collegetable',
            name='Address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='collegetable',
            name='Email',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AddField(
            model_name='collegetable',
            name='collegeName',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
