# Generated by Django 5.2.5 on 2025-09-02 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carriera', '0006_remove_collegetable_collegename_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collegetable',
            name='Email',
            field=models.CharField(max_length=50),
        ),
    ]
