# Generated by Django 5.2.5 on 2025-09-03 07:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carriera', '0007_alter_collegetable_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='hrregistertable',
            name='loginid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='carriera.logintable'),
        ),
    ]
