# Generated by Django 5.2.5 on 2025-09-03 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carriera', '0008_hrregistertable_loginid'),
    ]

    operations = [
        migrations.AddField(
            model_name='hrtable',
            name='Name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
