# Generated by Django 5.2.5 on 2025-09-03 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carriera', '0009_hrtable_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobroletable',
            name='Company_Name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='jobroletable',
            name='Description',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='jobroletable',
            name='Experience',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='jobroletable',
            name='Job_Role',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='jobroletable',
            name='Salary',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='jobroletable',
            name='Title',
            field=models.CharField(max_length=200),
        ),
    ]
