# Generated by Django 5.2.5 on 2025-09-03 09:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carriera', '0010_alter_jobroletable_company_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobroletable',
            old_name='Company_Name',
            new_name='company_name',
        ),
        migrations.AddField(
            model_name='jobroletable',
            name='HR_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='carriera.hrtable'),
            preserve_default=False,
        ),
    ]
