# Generated by Django 5.2.5 on 2025-09-21 05:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carriera', '0011_rename_company_name_jobroletable_company_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobroletable',
            name='HR_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carriera.hrregistertable'),
        ),
        migrations.RemoveField(
            model_name='coursetable',
            name='Duration',
        ),
        migrations.RemoveField(
            model_name='coursetable',
            name='Fees',
        ),
        migrations.RemoveField(
            model_name='coursetable',
            name='Video',
        ),
        migrations.AddField(
            model_name='coursetable',
            name='college',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='carriera.collegetable'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='HRTable',
        ),
    ]
