# Generated by Django 5.2.5 on 2025-10-05 08:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carriera', '0012_alter_jobroletable_hr_id_remove_coursetable_duration_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usertable',
            old_name='Phone_Number',
            new_name='PhoneNo',
        ),
        migrations.AlterField(
            model_name='usertable',
            name='LOGIN',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='carriera.logintable'),
        ),
    ]
