# Generated by Django 5.2.8 on 2025-11-08 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carriera', '0013_rename_phone_number_usertable_phoneno_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='collegetable',
            name='weblink',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='coursetable',
            name='duration',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
