# Generated by Django 5.2.8 on 2025-11-08 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carriera', '0014_collegetable_weblink_coursetable_duration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hrregistertable',
            name='CompanyId',
        ),
    ]
