# Generated by Django 5.2.5 on 2025-11-11 06:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carriera', '0015_remove_hrregistertable_companyid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobroletable',
            name='Title',
        ),
        migrations.RemoveField(
            model_name='jobroletable',
            name='company_name',
        ),
        migrations.AddField(
            model_name='jobroletable',
            name='category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='jobroletable',
            name='Experience',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='jobroletable',
            name='HR_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='carriera.hrregistertable'),
        ),
    ]
