# Generated by Django 5.2.5 on 2025-11-11 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carriera', '0016_remove_jobroletable_title_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserRequestTable',
        ),
    ]
